### ISSUE TITLE
Resolution of bounded type variables in a hierarchy

### ISSUE THREAD

**Issue by pholser** [xvik/generics-resolver#2]
Firstly: this is fantastic work! I appreciate your effort very much.

Not sure whether the behavior I see in [this gist](https://gist.github.com/pholser/74891e1c1b966c288b13) is a bug or intended behavior with release 2.0.0.

I was hoping that when resolving method `firstAndSecond` in the context of class `SelfPairProperties`, both `F` and `S` would resolve to `java.lang.Object`. `F` does, but there is no resolution for `S`.

**Comment by xvik** [comment]
Thank you very much!  Fixed in 2.0.1
